# Generated by Django 2.2.6 on 2019-10-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personsdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoes', models.BooleanField(default=False)),
                ('sneakers', models.BooleanField(default=False)),
                ('winter_shoes', models.BooleanField(default=False)),
                ('slippers', models.BooleanField(default=False)),
                ('person', models.ManyToManyField(to='personsdb.Persons')),
            ],
            options={
                'db_table': 'shoes',
            },
        ),
    ]
