# Generated by Django 2.2.6 on 2019-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personsdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planguages',
            name='name',
            field=models.CharField(choices=[('JS', 'JavaScript'), ('CPP', 'C++'), ('Py', 'Python')], max_length=20),
        ),
    ]
