# Generated by Django 2.2.6 on 2019-10-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personsdb', '0002_auto_20191026_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planguages',
            name='name',
            field=models.CharField(choices=[('JS', 'JavaScript'), ('CPP', 'C++'), ('Py', 'Python')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='planguages',
            name='typeofl',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
