from django.contrib import admin
from django.urls import path, include

urlpatterns = [
     path("", include("request_response_objects.home_page.urls",
                      namespace="home_page")),
     path("", include("request_response_objects.request_object.urls",
                      namespace="request_object")),
     path('admin/', admin.site.urls),
     path("", include("request_response_objects.query_dict.urls",
                      namespace="query_dict")),
     path("", include("request_response_objects.response_object.urls",
                      namespace="response_object")),
     path("", include("request_response_objects.response_redirect.urls",
                      namespace="redirect")),
     path("", include("request_response_objects.permanent_redirect.urls",
                      namespace="permanent_redirect")),
     path("", include("request_response_objects.not_modified.urls",
                      namespace="not_modified")),
     path("", include("request_response_objects.bad_request.urls",
                      namespace="bad_request")),
     path("", include("request_response_objects.not_found.urls",
                      namespace="not_found")),
     path("", include("request_response_objects.forbidden.urls",
                      namespace="forbidden")),
     path("", include("request_response_objects.not_allowed.urls",
                      namespace="not_allowed")),
     path("", include("request_response_objects.gone.urls",
                      namespace="gone")),
     path("", include("request_response_objects.server_error.urls",
                      namespace="server_error")),
     path("", include("request_response_objects.json_response.urls",
                      namespace="json_response")),
     path("", include("request_response_objects.streaming_http_response.urls",
                      namespace="streaming_http_response")),
     path("", include("request_response_objects.file_response.urls",
                      namespace="file_response")),
]
