# Generated by Django 3.0.6 on 2020-06-29 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Messages', '0005_privatemessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessage',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
